"""
Bot Layer — Nuntii  ⊡

Small, focused task bots that execute narrow, repeatable operations.
Unlike full agents, bots are stateless, single-purpose, and fast.

Charter Reference:
  "Small task bots that execute narrow actions:
   email bot, PDF bot, estimate bot, quote bot,
   punch bot, field-note bot, schedule bot"

Each bot:
- Has a single, well-defined purpose
- Takes structured input, returns structured output
- Is stateless (no memory between invocations)
- Can be invoked by any agent or the orchestrator

Glyph: ⊡ — task bot
"""

from __future__ import annotations

import uuid
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Callable, Awaitable

from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# Models
# ---------------------------------------------------------------------------

class BotStatus(str, Enum):
    """Bot operational status."""
    ACTIVE = "active"
    DISABLED = "disabled"
    DEPRECATED = "deprecated"


class Bot(BaseModel):
    """Definition of a task bot."""
    bot_id: str
    name: str
    glyph: str = "⊡"
    description: str
    
    # What it does
    input_schema: dict[str, Any] = Field(default_factory=dict)
    output_schema: dict[str, Any] = Field(default_factory=dict)
    
    # Metadata
    category: str = "general"
    version: str = "1.0.0"
    status: BotStatus = BotStatus.ACTIVE
    
    # Performance
    avg_latency_ms: float = 0.0
    invocation_count: int = 0
    error_count: int = 0


class BotResult(BaseModel):
    """Result from invoking a bot."""
    bot_id: str
    bot_name: str
    success: bool
    output: dict[str, Any] = Field(default_factory=dict)
    error: str | None = None
    duration_ms: float = 0.0
    invoked_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


# ---------------------------------------------------------------------------
# Bot Implementations
# ---------------------------------------------------------------------------

async def _email_bot_handler(input_data: dict[str, Any]) -> dict[str, Any]:
    """
    Email Bot — Formats and prepares emails for sending.
    
    Input: {to, subject, body, template?, attachments?}
    Output: {formatted_email, ready_to_send}
    """
    to = input_data.get("to", "")
    subject = input_data.get("subject", "")
    body = input_data.get("body", "")
    template = input_data.get("template", "default")
    
    # Format based on template
    if template == "bid_submission":
        formatted_body = f"Dear Team,\n\nPlease find attached our bid submission.\n\n{body}\n\nBest regards,\nSpatium Computationis"
    elif template == "field_update":
        formatted_body = f"Field Update:\n\n{body}\n\n— Sent from Spatium Computationis Field System"
    elif template == "rfi":
        formatted_body = f"REQUEST FOR INFORMATION\n\n{body}\n\nPlease respond at your earliest convenience."
    else:
        formatted_body = body

    return {
        "formatted_email": {
            "to": to,
            "subject": subject,
            "body": formatted_body,
            "template_used": template,
        },
        "ready_to_send": bool(to and subject and formatted_body),
        "character_count": len(formatted_body),
    }


async def _pdf_bot_handler(input_data: dict[str, Any]) -> dict[str, Any]:
    """
    PDF Bot — Prepares content for PDF generation.
    
    Input: {title, sections, document_type, project_id?}
    Output: {pdf_spec, page_count_estimate, ready}
    """
    title = input_data.get("title", "Untitled Document")
    sections = input_data.get("sections", [])
    document_type = input_data.get("document_type", "general")

    # Build PDF specification
    pdf_spec = {
        "title": title,
        "document_type": document_type,
        "header": {
            "logo": "spatium_computationis_logo",
            "title": title,
            "date": datetime.now(timezone.utc).strftime("%Y-%m-%d"),
        },
        "sections": sections,
        "footer": {
            "text": "Generated by Spatium Computationis ⌬",
            "page_numbers": True,
        },
    }

    # Estimate page count
    total_chars = sum(len(str(s.get("content", ""))) for s in sections)
    page_estimate = max(1, total_chars // 3000)

    return {
        "pdf_spec": pdf_spec,
        "page_count_estimate": page_estimate,
        "section_count": len(sections),
        "ready": len(sections) > 0,
    }


async def _estimate_bot_handler(input_data: dict[str, Any]) -> dict[str, Any]:
    """
    Estimate Bot — Quick calculation helper for estimates.
    
    Input: {items: [{description, quantity, unit_price}], markup_percent?, tax_percent?}
    Output: {subtotal, markup, tax, total, line_items}
    """
    items = input_data.get("items", [])
    markup_percent = input_data.get("markup_percent", 0.0)
    tax_percent = input_data.get("tax_percent", 0.0)

    line_items = []
    subtotal = 0.0

    for item in items:
        qty = item.get("quantity", 1)
        unit_price = item.get("unit_price", 0.0)
        line_total = qty * unit_price
        subtotal += line_total
        line_items.append({
            "description": item.get("description", ""),
            "quantity": qty,
            "unit_price": unit_price,
            "line_total": line_total,
        })

    markup = subtotal * (markup_percent / 100.0)
    after_markup = subtotal + markup
    tax = after_markup * (tax_percent / 100.0)
    total = after_markup + tax

    return {
        "line_items": line_items,
        "subtotal": round(subtotal, 2),
        "markup": round(markup, 2),
        "markup_percent": markup_percent,
        "tax": round(tax, 2),
        "tax_percent": tax_percent,
        "total": round(total, 2),
        "item_count": len(line_items),
    }


async def _quote_bot_handler(input_data: dict[str, Any]) -> dict[str, Any]:
    """
    Quote Bot — Normalizes and compares vendor quotes.
    
    Input: {quotes: [{vendor, items: [{description, price}], freight?, lead_time?}]}
    Output: {comparison, lowest_total, recommended}
    """
    quotes = input_data.get("quotes", [])

    comparison = []
    for quote in quotes:
        vendor = quote.get("vendor", "Unknown")
        items = quote.get("items", [])
        freight = quote.get("freight", 0.0)
        lead_time = quote.get("lead_time", "Unknown")

        items_total = sum(item.get("price", 0.0) for item in items)
        total = items_total + freight

        comparison.append({
            "vendor": vendor,
            "items_total": round(items_total, 2),
            "freight": round(freight, 2),
            "total": round(total, 2),
            "lead_time": lead_time,
            "item_count": len(items),
        })

    # Sort by total
    comparison.sort(key=lambda x: x["total"])
    
    recommended = comparison[0]["vendor"] if comparison else None

    return {
        "comparison": comparison,
        "quote_count": len(comparison),
        "lowest_total": comparison[0]["total"] if comparison else 0.0,
        "highest_total": comparison[-1]["total"] if comparison else 0.0,
        "recommended": recommended,
    }


async def _punch_bot_handler(input_data: dict[str, Any]) -> dict[str, Any]:
    """
    Punch Bot — Creates and formats punch list items.
    
    Input: {items: [{room, description, responsible?, photo_ref?}], project_id?}
    Output: {formatted_list, open_count, summary}
    """
    items = input_data.get("items", [])
    project_id = input_data.get("project_id")

    formatted_items = []
    for i, item in enumerate(items, 1):
        formatted_items.append({
            "item_number": i,
            "item_id": f"PI-{str(uuid.uuid4())[:8].upper()}",
            "room": item.get("room", "Unspecified"),
            "description": item.get("description", ""),
            "responsible_party": item.get("responsible", "TBD"),
            "photo_ref": item.get("photo_ref"),
            "status": "open",
            "created_at": datetime.now(timezone.utc).isoformat(),
        })

    # Group by room
    rooms = {}
    for item in formatted_items:
        room = item["room"]
        if room not in rooms:
            rooms[room] = []
        rooms[room].append(item)

    return {
        "project_id": project_id,
        "formatted_list": formatted_items,
        "by_room": rooms,
        "open_count": len(formatted_items),
        "room_count": len(rooms),
        "summary": f"{len(formatted_items)} punch items across {len(rooms)} rooms",
    }


async def _field_note_bot_handler(input_data: dict[str, Any]) -> dict[str, Any]:
    """
    Field Note Bot — Structures raw field notes into actionable data.
    
    Input: {raw_notes: str, worker?, location?, timestamp?}
    Output: {structured_note, action_items, issues_flagged}
    """
    raw_notes = input_data.get("raw_notes", "")
    worker = input_data.get("worker", "Unknown")
    location = input_data.get("location", "Unspecified")

    # Parse action items (lines starting with - or *)
    lines = raw_notes.strip().split("\n")
    action_items = []
    issues = []
    observations = []

    for line in lines:
        line = line.strip()
        if not line:
            continue
        lower = line.lower()
        if any(kw in lower for kw in ["issue", "problem", "broken", "damaged", "missing", "wrong"]):
            issues.append(line)
        elif line.startswith(("-", "*", "•")) or any(kw in lower for kw in ["need", "must", "should", "todo"]):
            action_items.append(line.lstrip("-*• "))
        else:
            observations.append(line)

    return {
        "structured_note": {
            "worker": worker,
            "location": location,
            "timestamp": input_data.get("timestamp", datetime.now(timezone.utc).isoformat()),
            "observations": observations,
            "action_items": action_items,
            "issues": issues,
        },
        "action_item_count": len(action_items),
        "issue_count": len(issues),
        "requires_attention": len(issues) > 0,
    }


async def _schedule_bot_handler(input_data: dict[str, Any]) -> dict[str, Any]:
    """
    Schedule Bot — Calculates scheduling and timeline logic.
    
    Input: {tasks: [{name, duration_hours, depends_on?}], start_date?, work_hours_per_day?}
    Output: {timeline, total_duration, critical_path, end_date}
    """
    tasks = input_data.get("tasks", [])
    start_date = input_data.get("start_date", datetime.now(timezone.utc).strftime("%Y-%m-%d"))
    work_hours = input_data.get("work_hours_per_day", 8)

    # Simple forward-pass scheduling
    task_map = {}
    timeline = []
    current_hour = 0

    for task in tasks:
        name = task.get("name", "")
        duration = task.get("duration_hours", 0)
        depends_on = task.get("depends_on", [])

        # Find earliest start (after all dependencies)
        earliest_start = 0
        for dep in depends_on:
            if dep in task_map:
                dep_end = task_map[dep]["end_hour"]
                earliest_start = max(earliest_start, dep_end)

        start_hour = max(current_hour, earliest_start)
        end_hour = start_hour + duration

        task_entry = {
            "name": name,
            "start_hour": start_hour,
            "end_hour": end_hour,
            "duration_hours": duration,
            "start_day": start_hour / work_hours,
            "end_day": end_hour / work_hours,
            "depends_on": depends_on,
        }
        task_map[name] = task_entry
        timeline.append(task_entry)

    total_hours = max((t["end_hour"] for t in timeline), default=0)
    total_days = total_hours / work_hours

    return {
        "timeline": timeline,
        "total_duration_hours": total_hours,
        "total_duration_days": round(total_days, 1),
        "work_hours_per_day": work_hours,
        "start_date": start_date,
        "task_count": len(timeline),
    }


# ---------------------------------------------------------------------------
# Bot Registry
# ---------------------------------------------------------------------------

# Type for bot handlers
BotHandler = Callable[[dict[str, Any]], Awaitable[dict[str, Any]]]


class BotRegistry:
    """Registry of all available task bots."""

    def __init__(self):
        self._bots: dict[str, Bot] = {}
        self._handlers: dict[str, BotHandler] = {}
        self._register_defaults()

    def _register_defaults(self) -> None:
        """Register all built-in bots."""
        defaults = [
            ("email", "⊡✉", "Email Bot", "Formats and prepares emails for sending", "communication", _email_bot_handler),
            ("pdf", "⊡📄", "PDF Bot", "Prepares content for PDF generation", "documents", _pdf_bot_handler),
            ("estimate", "⊡💰", "Estimate Bot", "Quick calculation helper for estimates", "estimating", _estimate_bot_handler),
            ("quote", "⊡📋", "Quote Bot", "Normalizes and compares vendor quotes", "estimating", _quote_bot_handler),
            ("punch", "⊡✓", "Punch Bot", "Creates and formats punch list items", "field", _punch_bot_handler),
            ("field_note", "⊡📝", "Field Note Bot", "Structures raw field notes into actionable data", "field", _field_note_bot_handler),
            ("schedule", "⊡📅", "Schedule Bot", "Calculates scheduling and timeline logic", "workflow", _schedule_bot_handler),
        ]

        for bot_id, glyph, name, desc, category, handler in defaults:
            self._bots[bot_id] = Bot(
                bot_id=bot_id,
                name=name,
                glyph=glyph,
                description=desc,
                category=category,
            )
            self._handlers[bot_id] = handler

    def register(self, bot_id: str, bot: Bot, handler: BotHandler) -> None:
        """Register a custom bot."""
        self._bots[bot_id] = bot
        self._handlers[bot_id] = handler

    def get(self, bot_id: str) -> Bot | None:
        """Get bot definition by ID."""
        return self._bots.get(bot_id)

    def list_all(self) -> list[Bot]:
        """List all registered bots."""
        return [b for b in self._bots.values() if b.status == BotStatus.ACTIVE]

    def list_by_category(self, category: str) -> list[Bot]:
        """List bots in a specific category."""
        return [
            b for b in self._bots.values()
            if b.category == category and b.status == BotStatus.ACTIVE
        ]

    async def invoke(self, bot_id: str, input_data: dict[str, Any]) -> BotResult:
        """Invoke a bot with input data."""
        import time

        bot = self._bots.get(bot_id)
        if not bot:
            return BotResult(
                bot_id=bot_id,
                bot_name="unknown",
                success=False,
                error=f"Bot '{bot_id}' not found",
            )

        if bot.status != BotStatus.ACTIVE:
            return BotResult(
                bot_id=bot_id,
                bot_name=bot.name,
                success=False,
                error=f"Bot '{bot_id}' is {bot.status.value}",
            )

        handler = self._handlers.get(bot_id)
        if not handler:
            return BotResult(
                bot_id=bot_id,
                bot_name=bot.name,
                success=False,
                error=f"No handler registered for bot '{bot_id}'",
            )

        start = time.perf_counter()
        try:
            output = await handler(input_data)
            duration_ms = (time.perf_counter() - start) * 1000

            # Update stats
            bot.invocation_count += 1
            bot.avg_latency_ms = (
                (bot.avg_latency_ms * (bot.invocation_count - 1) + duration_ms)
                / bot.invocation_count
            )

            return BotResult(
                bot_id=bot_id,
                bot_name=bot.name,
                success=True,
                output=output,
                duration_ms=duration_ms,
            )

        except Exception as e:
            duration_ms = (time.perf_counter() - start) * 1000
            bot.error_count += 1
            bot.invocation_count += 1

            return BotResult(
                bot_id=bot_id,
                bot_name=bot.name,
                success=False,
                error=str(e),
                duration_ms=duration_ms,
            )


# ---------------------------------------------------------------------------
# Global Instance & Convenience Functions
# ---------------------------------------------------------------------------

_global_registry: BotRegistry | None = None


def _get_registry() -> BotRegistry:
    global _global_registry
    if _global_registry is None:
        _global_registry = BotRegistry()
    return _global_registry


def get_bot(bot_id: str) -> Bot | None:
    """Get a bot by ID."""
    return _get_registry().get(bot_id)


def list_bots(category: str | None = None) -> list[Bot]:
    """List all bots, optionally filtered by category."""
    if category:
        return _get_registry().list_by_category(category)
    return _get_registry().list_all()


async def invoke_bot(bot_id: str, input_data: dict[str, Any]) -> BotResult:
    """Invoke a bot with input data."""
    return await _get_registry().invoke(bot_id, input_data)
